## The Evolution of Life Expectancy

In [2]:
import plotly_express as px
import pandas as pd

 (Clio-Infra up to 1949; UN Population Division for 1950 to 2015) (years)

In [51]:
dateparse = lambda x: pd.datetime.strptime(x, '%Y')

df = pd.read_csv('life-expectancy.csv', parse_dates=['Year'], date_parser=dateparse).dropna()

start_date = '1700-01-01 00:00:00'
end_date = '2015-01-01 00:00:00'

mask = (df['Year'] > start_date) & (df['Year'] <= end_date)

TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'

In [48]:
df

            Entity Code                 Year  Life expectancy
0      Afghanistan  AFG  1950-01-01 00:00:00        27.537001
1      Afghanistan  AFG  1951-01-01 00:00:00        27.809999
2      Afghanistan  AFG  1952-01-01 00:00:00        28.350000
3      Afghanistan  AFG  1953-01-01 00:00:00        28.879999
4      Afghanistan  AFG  1954-01-01 00:00:00        29.399000
5      Afghanistan  AFG  1955-01-01 00:00:00        29.907000
6      Afghanistan  AFG  1956-01-01 00:00:00        30.403999
7      Afghanistan  AFG  1957-01-01 00:00:00        30.891001
8      Afghanistan  AFG  1958-01-01 00:00:00        31.367001
9      Afghanistan  AFG  1959-01-01 00:00:00        31.834000
10     Afghanistan  AFG  1960-01-01 00:00:00        32.292000
11     Afghanistan  AFG  1961-01-01 00:00:00        32.742001
12     Afghanistan  AFG  1962-01-01 00:00:00        33.185001
13     Afghanistan  AFG  1963-01-01 00:00:00        33.624001
14     Afghanistan  AFG  1964-01-01 00:00:00        34.060001
15     Afghanistan  AFG  1965-01-01 00:00:00        34.494999
16     Afghanistan  AFG  1966-01-01 00:00:00        34.928001
17     Afghanistan  AFG  1967-01-01 00:00:00        35.361000
18     Afghanistan  AFG  1968-01-01 00:00:00        35.796001
19     Afghanistan  AFG  1969-01-01 00:00:00        36.234001
20     Afghanistan  AFG  1970-01-01 00:00:00        36.678001
21     Afghanistan  AFG  1971-01-01 00:00:00        37.127998
22     Afghanistan  AFG  1972-01-01 00:00:00        37.587002
23     Afghanistan  AFG  1973-01-01 00:00:00        38.056000
24     Afghanistan  AFG  1974-01-01 00:00:00        38.540001
25     Afghanistan  AFG  1975-01-01 00:00:00        39.039001
26     Afghanistan  AFG  1976-01-01 00:00:00        39.556000
27     Afghanistan  AFG  1977-01-01 00:00:00        40.091999
28     Afghanistan  AFG  1978-01-01 00:00:00        40.650002
29     Afghanistan  AFG  1979-01-01 00:00:00        41.234001
...            ...  ...                  ...              ...
17864     Zimbabwe  ZWE  1986-01-01 00:00:00        60.816002
17865     Zimbabwe  ZWE  1987-01-01 00:00:00        60.410999
17866     Zimbabwe  ZWE  1988-01-01 00:00:00        59.793999
17867     Zimbabwe  ZWE  1989-01-01 00:00:00        58.971001
17868     Zimbabwe  ZWE  1990-01-01 00:00:00        57.944000
17869     Zimbabwe  ZWE  1991-01-01 00:00:00        56.720001
17870     Zimbabwe  ZWE  1992-01-01 00:00:00        55.337002
17871     Zimbabwe  ZWE  1993-01-01 00:00:00        53.854000
17872     Zimbabwe  ZWE  1994-01-01 00:00:00        52.328999
17873     Zimbabwe  ZWE  1995-01-01 00:00:00        50.811001
17874     Zimbabwe  ZWE  1996-01-01 00:00:00        49.340000
17875     Zimbabwe  ZWE  1997-01-01 00:00:00        47.955002
17876     Zimbabwe  ZWE  1998-01-01 00:00:00        46.705002
17877     Zimbabwe  ZWE  1999-01-01 00:00:00        45.646999
17878     Zimbabwe  ZWE  2000-01-01 00:00:00        44.841000
17879     Zimbabwe  ZWE  2001-01-01 00:00:00        44.326000
17880     Zimbabwe  ZWE  2002-01-01 00:00:00        44.109001
17881     Zimbabwe  ZWE  2003-01-01 00:00:00        44.188000
17882     Zimbabwe  ZWE  2004-01-01 00:00:00        44.570999
17883     Zimbabwe  ZWE  2005-01-01 00:00:00        45.282001
17884     Zimbabwe  ZWE  2006-01-01 00:00:00        46.344002
17885     Zimbabwe  ZWE  2007-01-01 00:00:00        47.719002
17886     Zimbabwe  ZWE  2008-01-01 00:00:00        49.337002
17887     Zimbabwe  ZWE  2009-01-01 00:00:00        51.122002
17888     Zimbabwe  ZWE  2010-01-01 00:00:00        52.974998
17889     Zimbabwe  ZWE  2011-01-01 00:00:00        54.799999
17890     Zimbabwe  ZWE  2012-01-01 00:00:00        56.515999
17891     Zimbabwe  ZWE  2013-01-01 00:00:00        58.053001
17892     Zimbabwe  ZWE  2014-01-01 00:00:00        59.360001
17893     Zimbabwe  ZWE  2015-01-01 00:00:00        60.397999

[15386 rows x 4 columns]

In [41]:
px.choropleth(df, locations="Code", color="Life expectancy", hover_name="Entity", animation_frame="Year",
             color_continuous_scale=px.colors.sequential.Greens, width=800, projection="natural earth")

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1543-01-01 00:00:00