## How Our Dating Pattern Has Changed

Data Source: https://data.stanford.edu/hcmst2017

Dictionary: https://www.visualcapitalist.com/online-dating-big-business/

In [11]:
import pandas as pd
from datetime import datetime

data = pd.io.stata.read_stata('HCMST 2017 fresh sample for public sharing draft v1.1.dta')
data.to_csv('my_stata_file.csv')

In [43]:
df = pd.read_csv('my_stata_file.csv', low_memory=False)
df.head()

,Unnamed: 0,CaseID,CASEID_NEW,qflag,weight1,weight1_freqwt,weight2,weight1a,weight1a_freqwt,weight_combo,...,hcm2017q24_met_through_family,hcm2017q24_met_through_friend,hcm2017q24_met_through_as_nghbrs,hcm2017q24_met_as_through_cowork,w6_subject_race,interracial_5cat,partner_mother_yrsed,subject_mother_yrsed,partner_yrsed,subject_yrsed
0,0,2,2014039,Qualified,NaN,NaN,0.8945,NaN,NaN,0.277188,...,no,no,no,no,White,no,12.0,14.0,12.0,14.0
1,1,3,2019003,Qualified,0.9078,71115.0,NaN,0.9026,70707.0,1.020621,...,no,no,no,yes,White,no,12.0,16.0,17.0,17.0
2,2,5,2145527,Qualified,0.7205,56442.0,NaN,0.7164,56121.0,0.810074,...,no,no,no,no,White,no,9.0,7.5,14.0,17.0
3,3,6,2648857,Qualified,1.2597,98682.0,1.3507,1.2524,98110.0,0.418556,...,no,no,no,no,White,no,16.0,12.0,12.0,12.0
4,4,7,2623465,Qualified,0.8686,68044.0,NaN,0.8636,67652.0,0.976522,...,no,no,yes,no,White,no,14.0,17.0,16.0,16.0

In [51]:
first_met = df.loc[(df['Q21A_Year'] != 'Refused') & df.loc[(df['Q21A_Year'] != 'NaN')]]
first_met["Q21A_Year"] = pd.to_numeric(first_met["Q21A_Year"])
# bins = pd.cut(df['Q21A_Year'], [1960, 1969, 1970, 1979, 1980, 1989, 1990, 1999, 2000, 2009, 2010, 2019])

/opt/conda/lib/python3.6/site-packages/pandas/core/indexes/base.py:3772: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)

ValueError: operands could not be broadcast together with shapes (12460500,) (3550,)

In [47]:
first_met.Q21A_Year.unique

<bound method Series.unique of 0          NaN
1       1983.0
2       2006.0
3          NaN
4       1983.0
5       1981.0
6       1966.0
7       1967.0
8          NaN
9          NaN
10      2008.0
11         NaN
12         NaN
13         NaN
14      2007.0
15      2002.0
16      2007.0
17      2002.0
18      2004.0
19      1973.0
20      1995.0
21         NaN
22         NaN
23      2008.0
24      2000.0
25      1990.0
26         NaN
27      2014.0
28      2012.0
29      2010.0
         ...
3480    1994.0
3481    2011.0
3482    2015.0
3483    2008.0
3484    2010.0
3485    2011.0
3486       NaN
3487    1996.0
3488    1987.0
3489    1998.0
3490    2014.0
3491    2000.0
3492       NaN
3493       NaN
3494       NaN
3495    2016.0
3496    1998.0
3497    2011.0
3498    2015.0
3499    2013.0
3500    1978.0
3501    2016.0
3502    1996.0
3503    1994.0
3504       NaN
3505    2015.0
3506    2016.0
3507    2012.0
3508    2014.0
3509    2015.0
Name: Q21A_Year, Length: 3474, dtype: float64>

In [15]:
df['Date First Met'] = df.apply(lambda row: datetime(
                              row['Q21A_Year'], row['Q21A_Month']), axis=1)

TypeError: ('integer argument expected, got float', 'occurred at index 0')